import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import householdsRouter from "./households";
import podsRouter from "./pods";
import eventsRouter from "./events";
import carpoolsRouter from "./carpools";
import trailheadsRouter from "./trailheads";
import messagesRouter from "./messages";
import invitesRouter from "./invites";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import teamDocumentsRouter from "./team-documents";
import notificationsRouter from "./notifications";
import calendarRouter from "./calendar";
import volunteerTasksRouter from "./volunteerTasks";
import boardRouter from "./board";
import seasonsRouter from "./seasons";
import familyInvitesRouter from "./family-invites";
import settingsRouter from "./settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(usersRouter);
router.use(householdsRouter);
router.use(podsRouter);
router.use(eventsRouter);
router.use(carpoolsRouter);
router.use(trailheadsRouter);
router.use(messagesRouter);
router.use(invitesRouter);
router.use(storageRouter);
router.use(teamDocumentsRouter);
router.use(notificationsRouter);
router.use(calendarRouter);
router.use(volunteerTasksRouter);
router.use(boardRouter);
router.use(seasonsRouter);
router.use(familyInvitesRouter);
router.use(settingsRouter);

export default router;
